env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gofer
    id: "gofer"
    binary: gofer
    goos:
      - linux
      - darwin

  - main: ./cmd/spire
    id: "spire"
    binary: spire
    goos:
      - linux
      # - darwin

  - main: ./cmd/ghost
    id: "ghost"
    binary: ghost
    goos:
      - linux
      - darwin

  - main: ./cmd/spectre
    id: "spectre"
    binary: spectre
    goos:
      - linux
      - darwin

archives:
  - id: "gofer"
    builds:
      - gofer
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: "spire"
    builds:
      - spire
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: "ghost"
    builds:
      - ghost
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: "spectre"
    builds:
      - spectre
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

