env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: spire
    main: ./cmd/spire
    binary: spire
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X github.com/chronicleprotocol/oracle-suite.Version={{.Version}}"

  - id: ghost
    main: ./cmd/ghost
    binary: ghost
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X github.com/chronicleprotocol/oracle-suite.Version={{.Version}}"

  - id: spectre
    main: ./cmd/spectre
    binary: spectre
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X github.com/chronicleprotocol/oracle-suite.Version={{.Version}}"

archives:
  - id: spire
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - spire

  - id: ghost
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - ghost

  - id: spectre
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - spectre

#nfpms:
#  - id: feed
#    package_name: chronicle-feed
#    vendor: Chronicle Labs
#    homepage: https://chroniclelabs.org/
#    maintainer: Chronicle Labs <hello@chroniclelabs.org>
#    license: AGPL-3.0
#    formats:
#      - deb
#    section: default
#    priority: extra
#    scripts:
#      preinstall: "scripts/preinstall.sh"
#      postinstall: "scripts/postinstall.sh"
