version: '3'
services:
  bootstrap:
    hostname: "bootstrap.local"
    image: ghcr.io/chronicleprotocol/spire:0.0.0-dev.0
    network_mode: "host"
    command: [ "bootstrap" ]
    environment:
      CFG_LIBP2P_BOOTSTRAP_ADDRS: ""
      CFG_LIBP2P_PK_SEED: "FFDCBA9876543210FEDCBA98765432100123456789ABCDEF0123456789ABCDEF"

  spire:
    image: ghcr.io/chronicleprotocol/spire:0.0.0-dev.0
    network_mode: "host"
    command: [ "stream" ]
    environment:
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8090"

  ghost1:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_ETH_FROM: ${ETH_FROM_A}
      CFG_ETH_KEYS: ${ETH_KEYS_A}
      CFG_ETH_PASS: ""
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_WEBAPI_ENABLE: 0
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8011"
      CFG_GHOST_INTERVAL: 10
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xB18C42Ec40A258eD7970CCa8a532A90bd2DBacaB"
      CFG_GHOST_PAIRS: "BTC/USD"
  ghost2:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_ETH_FROM: ${ETH_FROM_B}
      CFG_ETH_KEYS: ${ETH_KEYS_B}
      CFG_ETH_PASS: ""
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_WEBAPI_ENABLE: 0
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8012"
      CFG_GHOST_INTERVAL: 10
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xB18C42Ec40A258eD7970CCa8a532A90bd2DBacaB"
      CFG_GHOST_PAIRS: "BTC/USD"
  ghost3:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_ETH_FROM: ${ETH_FROM_C}
      CFG_ETH_KEYS: ${ETH_KEYS_C}
      CFG_ETH_PASS: ""
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_WEBAPI_ENABLE: 0
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8013"
      CFG_GHOST_INTERVAL: 10
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xB18C42Ec40A258eD7970CCa8a532A90bd2DBacaB"
      CFG_GHOST_PAIRS: "BTC/USD"

  spectre1:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      CFG_SPECTRE_TARGET_NETWORK: "ethereum-goerli"
      CFG_ETH_FROM: ${ETH_FROM_D}
      CFG_ETH_KEYS: ${ETH_KEYS_D}
      CFG_ETH_PASS: ""
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_WEBAPI_ENABLE: 0
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8031"
      CFG_ETH_RPC_URLS: ${ETH_RPCS} # comma separated list of ethereum rpc urls, set to empty string to disable
      CFG_ETH_CHAIN_ID: ${ETH_CHID} # ethereum chain id
      CFG_ARB_RPC_URLS: ${ARB_RPCS} # comma separated list of arbitrum rpc urls, set to empty string to disable
      CFG_ARB_CHAIN_ID: ${ARB_CHID} # arbitrum chain id
      CFG_OPT_RPC_URLS: ${OPT_RPCS} # comma separated list of optimism rpc urls, set to empty string to disable
      CFG_OPT_CHAIN_ID: ${OPT_CHID} # optimism chain id
  spectre2:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      CFG_SPECTRE_TARGET_NETWORK: "arbitrum-goerli"
      CFG_ETH_FROM: ${ETH_FROM_E}
      CFG_ETH_KEYS: ${ETH_KEYS_E}
      CFG_ETH_PASS: ""
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_WEBAPI_ENABLE: 0
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8032"
      CFG_ETH_RPC_URLS: ${ETH_RPCS} # comma separated list of ethereum rpc urls, set to empty string to disable
      CFG_ETH_CHAIN_ID: ${ETH_CHID} # ethereum chain id
      CFG_ARB_RPC_URLS: ${ARB_RPCS} # comma separated list of arbitrum rpc urls, set to empty string to disable
      CFG_ARB_CHAIN_ID: ${ARB_CHID} # arbitrum chain id
      CFG_OPT_RPC_URLS: ${OPT_RPCS} # comma separated list of optimism rpc urls, set to empty string to disable
      CFG_OPT_CHAIN_ID: ${OPT_CHID} # optimism chain id
  spectre3:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      CFG_SPECTRE_TARGET_NETWORK: "optimism-goerli"
      CFG_ETH_FROM: ${ETH_FROM_F}
      CFG_ETH_KEYS: ${ETH_KEYS_F}
      CFG_ETH_PASS: ""
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_WEBAPI_ENABLE: 0
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8033"
      CFG_ETH_RPC_URLS: ${ETH_RPCS} # comma separated list of ethereum rpc urls, set to empty string to disable
      CFG_ETH_CHAIN_ID: ${ETH_CHID} # ethereum chain id
      CFG_ARB_RPC_URLS: ${ARB_RPCS} # comma separated list of arbitrum rpc urls, set to empty string to disable
      CFG_ARB_CHAIN_ID: ${ARB_CHID} # arbitrum chain id
      CFG_OPT_RPC_URLS: ${OPT_RPCS} # comma separated list of optimism rpc urls, set to empty string to disable
      CFG_OPT_CHAIN_ID: ${OPT_CHID} # optimism chain id
