version: '3'
services:
  bootstrap:
    hostname: "bootstrap.local"
    image: ghcr.io/chronicleprotocol/spire:0.0.0-dev.0
    network_mode: "host"
    command: [ "bootstrap" ]
    environment:
      CFG_LIBP2P_PK_SEED: "FFDCBA9876543210FEDCBA98765432100123456789ABCDEF0123456789ABCDEF"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: ""
      # Consider using this to connect bootstrap nodes to each other
      #CFG_LIBP2P_DIRECT_PEERS_ADDRS: "/ip4/.../"

  spire:
    image: ghcr.io/chronicleprotocol/spire:0.0.0-dev.0
    network_mode: "host"
    command: [ "stream", "greet/v1", "musig_signature/v1", "musig_optimistic_signature/v1" ]
    environment:
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8090"

      CFG_WEBAPI_ENABLE: 0

  ghost1:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_ETH_FROM: ${ETH_FROM_A}
      CFG_ETH_KEYS: ${ETH_KEYS_A}
      CFG_ETH_PASS: ""

      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8011"

      CFG_WEBAPI_ENABLE: 1
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xB18C42Ec40A258eD7970CCa8a532A90bd2DBacaB"
      CFG_WEBAPI_RPC_CLIENT: "ethereum"

      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10
    volumes:
      - ./config-defaults.hcl:/usr/share/chronicle-suite/config-defaults.hcl
      - ./config-ethereum.hcl:/usr/share/chronicle-suite/config-ethereum.hcl
      - ./config-ghost.hcl:/usr/share/chronicle-suite/config-ghost.hcl
      - ./config-gofer.hcl:/usr/share/chronicle-suite/config-gofer.hcl
      - ./config-spectre.hcl:/usr/share/chronicle-suite/config-spectre.hcl
      - ./config-spire.hcl:/usr/share/chronicle-suite/config-spire.hcl
      - ./config-transport.hcl:/usr/share/chronicle-suite/config-transport.hcl
  ghost2:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_ETH_FROM: ${ETH_FROM_B}
      CFG_ETH_KEYS: ${ETH_KEYS_B}
      CFG_ETH_PASS: ""

      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8012"

      CFG_WEBAPI_ENABLE: 0
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xB18C42Ec40A258eD7970CCa8a532A90bd2DBacaB"
      CFG_WEBAPI_RPC_CLIENT: "ethereum"

      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10
  ghost3:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_ETH_FROM: ${ETH_FROM_C}
      CFG_ETH_KEYS: ${ETH_KEYS_C}
      CFG_ETH_PASS: ""

      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8013"

      CFG_WEBAPI_ENABLE: 0
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xB18C42Ec40A258eD7970CCa8a532A90bd2DBacaB"
      CFG_WEBAPI_RPC_CLIENT: "ethereum"

      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10
  ghost4:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_ETH_FROM: ${ETH_FROM_D}
      CFG_ETH_KEYS: ${ETH_KEYS_D}
      CFG_ETH_PASS: ""

      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8014"

      CFG_WEBAPI_ENABLE: 0
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xB18C42Ec40A258eD7970CCa8a532A90bd2DBacaB"
      CFG_WEBAPI_RPC_CLIENT: "ethereum"

      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10

  spectre1:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      #      CFG_ETH_FROM: ${ETH_FROM_E}
      #      CFG_ETH_KEYS: ${ETH_KEYS_E}
      #      CFG_ETH_PASS: ""
      CFG_RPC_URLS: ${ETH_RPCS}
      CFG_CHAIN_ID: ${ETH_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8022"

      CFG_WEBAPI_ENABLE: 0

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "ethereum-goerli"
  spectre2:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      #      CFG_ETH_FROM: ${ETH_FROM_F}
      #      CFG_ETH_KEYS: ${ETH_KEYS_F}
      #      CFG_ETH_PASS: ""
      CFG_RPC_URLS: ${OPT_RPCS}
      CFG_CHAIN_ID: ${OPT_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8023"

      CFG_WEBAPI_ENABLE: 0

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "optimism-goerli"
  spectre3:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      #      CFG_ETH_FROM: ${ETH_FROM_G}
      #      CFG_ETH_KEYS: ${ETH_KEYS_G}
      #      CFG_ETH_PASS: ""
      CFG_RPC_URLS: ${ARB_RPCS}
      CFG_CHAIN_ID: ${ARB_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8024"

      CFG_WEBAPI_ENABLE: 0

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "arbitrum-goerli"
  spectre4:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      #      CFG_ETH_FROM: ${ETH_FROM_H}
      #      CFG_ETH_KEYS: ${ETH_KEYS_H}
      #      CFG_ETH_PASS: ""
      CFG_RPC_URLS: ${SEP_RPCS}
      CFG_CHAIN_ID: ${SEP_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWRhP3CQxqtmZVU7n9ubfH4QPxtY8fxa7PDsoNPkQ66wF9"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8021"

      CFG_WEBAPI_ENABLE: 0

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "sep"
    volumes:
      - ./config-defaults.hcl:/usr/share/chronicle-suite/config-defaults.hcl
      - ./config-ethereum.hcl:/usr/share/chronicle-suite/config-ethereum.hcl
      - ./config-ghost.hcl:/usr/share/chronicle-suite/config-ghost.hcl
      - ./config-gofer.hcl:/usr/share/chronicle-suite/config-gofer.hcl
      - ./config-spectre.hcl:/usr/share/chronicle-suite/config-spectre.hcl
      - ./config-spire.hcl:/usr/share/chronicle-suite/config-spire.hcl
      - ./config-transport.hcl:/usr/share/chronicle-suite/config-transport.hcl
