version: '3'
services:
  bootstrap:
    hostname: "bootstrap.local"
    image: ghcr.io/chronicleprotocol/spire:0.0.0-dev.0
    network_mode: "host"
    command: [ "bootstrap" ]
    environment:
      CFG_LIBP2P_PK_SEED: "FEDCBA9876543210FEDCBA98765432100123456789ABCDEF0123456789ABCDEF"
      CFG_LIBP2P_BOOTSTRAP_ADDRS: ""
      # Consider using this to connect bootstrap nodes to each other
      #CFG_LIBP2P_DIRECT_PEERS_ADDRS: "/ip4/.../"

  spire:
    image: ghcr.io/chronicleprotocol/spire:0.0.0-dev.0
    network_mode: "host"
    command: [ "stream", "greet/v1", "musig_signature/v1", "musig_optimistic_signature/v1" ]
    environment:
      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8090"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "0.0.0.0:8080"
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "" # disable sending messages
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: ""
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""

  ghost1:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default ETH key
      CFG_ETH_FROM: ${ETH_FROM_A}
      CFG_ETH_KEYS: ${ETH_KEYS_A}
      CFG_ETH_PASS: ""

      # ethereum RPC client
      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${SEP_RPCS}
      CFG_CHAIN_ID: ${SEP_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8011"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "" # disable incoming connections
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "127.0.0.1:9050"
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xfA2EFCb2EfCf65F9E36379716C28b12Fb1F07B83" # relays
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""
  ghost2:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default ETH key
      CFG_ETH_FROM: ${ETH_FROM_B}
      CFG_ETH_KEYS: ${ETH_KEYS_B}
      CFG_ETH_PASS: ""

      # ethereum RPC client
      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${SEP_RPCS}
      CFG_CHAIN_ID: ${SEP_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8012"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "" # disable incoming connections
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "127.0.0.1:9050"
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xfA2EFCb2EfCf65F9E36379716C28b12Fb1F07B83" # relays
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""
  ghost3:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default ETH key
      CFG_ETH_FROM: ${ETH_FROM_C}
      CFG_ETH_KEYS: ${ETH_KEYS_C}
      CFG_ETH_PASS: ""

      # ethereum RPC client
      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${SEP_RPCS}
      CFG_CHAIN_ID: ${SEP_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8013"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "" # disable incoming connections
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "127.0.0.1:9050"
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xfA2EFCb2EfCf65F9E36379716C28b12Fb1F07B83" # relays
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""
  ghost4:
    image: ghcr.io/chronicleprotocol/ghost:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_GHOST_PAIRS: "ETH/USD"
      CFG_GHOST_INTERVAL: 10

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default ETH key
      CFG_ETH_FROM: ${ETH_FROM_D}
      CFG_ETH_KEYS: ${ETH_KEYS_D}
      CFG_ETH_PASS: ""

      # ethereum RPC client
      CFG_ETH_RPC_URLS: ${RPCS}
      CFG_ETH_CHAIN_ID: ${CHID}

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${SEP_RPCS}
      CFG_CHAIN_ID: ${SEP_CHID}

      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8014"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "" # disable incoming connections
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "127.0.0.1:9050"
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: "0xfA2EFCb2EfCf65F9E36379716C28b12Fb1F07B83" # relays
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""

  spectre1:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    command: [ "run" ]
    environment:
      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "ethereum-goerli"

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${ETH_RPCS}
      CFG_CHAIN_ID: ${ETH_CHID}

      # libp2p
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8021"
      CFG_CHAIN_GAS_FEE_MULTIPLIER: 1
      CFG_CHAIN_GAS_PRIORITY_FEE_MULTIPLIER: 1
      CFG_CHAIN_MAX_GAS_FEE: 0
      CFG_CHAIN_MAX_GAS_PRIORITY_FEE: 0
      CFG_CHAIN_MAX_GAS_LIMIT: 0

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "0.0.0.0:8081"
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "" # disable sending messages
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: ""
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""
  spectre2:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "optimism-goerli"

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${OPT_RPCS}
      CFG_CHAIN_ID: ${OPT_CHID}
      CFG_CHAIN_GAS_FEE_MULTIPLIER: 1
      CFG_CHAIN_GAS_PRIORITY_FEE_MULTIPLIER: 1
      CFG_CHAIN_MAX_GAS_FEE: 0
      CFG_CHAIN_MAX_GAS_PRIORITY_FEE: 0
      CFG_CHAIN_MAX_GAS_LIMIT: 0

      # libp2p
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8022"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "0.0.0.0:8082"
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "" # disable sending messages
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: ""
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""
  spectre3:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "arbitrum-goerli"

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${ARB_RPCS}
      CFG_CHAIN_ID: ${ARB_CHID}
      CFG_CHAIN_GAS_FEE_MULTIPLIER: 1
      CFG_CHAIN_GAS_PRIORITY_FEE_MULTIPLIER: 1
      CFG_CHAIN_MAX_GAS_FEE: 0
      CFG_CHAIN_MAX_GAS_PRIORITY_FEE: 0
      CFG_CHAIN_MAX_GAS_LIMIT: 0

      # libp2p
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8023"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "0.0.0.0:8083"
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "" # disable sending messages
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: ""
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""
  spectre4:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    network_mode: "host"
    environment:
      CFG_SPECTRE_PAIRS: "ETH/USD"
      CFG_SPECTRE_TARGET_NETWORK: "sep"

      CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C},${ETH_FROM_D}"

      # default RPC client
      CFG_CHAIN_RPC_URLS: ${SEP_RPCS}
      CFG_CHAIN_ID: ${SEP_CHID}
      CFG_CHAIN_GAS_FEE_MULTIPLIER: 1
      CFG_CHAIN_GAS_PRIORITY_FEE_MULTIPLIER: 1
      CFG_CHAIN_MAX_GAS_FEE: 0
      CFG_CHAIN_MAX_GAS_PRIORITY_FEE: 0
      CFG_CHAIN_MAX_GAS_LIMIT: 0

      # libp2p
      CFG_LIBP2P_BOOTSTRAP_ADDRS: "/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      CFG_LIBP2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/8024"

      # webapi
      CFG_WEBAPI_ENABLE: 0
      ## receiving
      CFG_WEBAPI_LISTEN_ADDR: "0.0.0.0:8084"
      ## sending
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "" # disable sending messages
      ### on-chain address book
      CFG_WEBAPI_ETH_ADDR_BOOK: ""
      ### local address book
      CFG_WEBAPI_STATIC_ADDR_BOOK: ""
