//  Copyright (C) 2021-2023 Chronicle Labs, Inc.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Affero General Public License as
//  published by the Free Software Foundation, either version 3 of the
//  License, or (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Affero General Public License for more details.
//
//  You should have received a copy of the GNU Affero General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"os"
)

var args = []string{"gofer", "-c", "../../config.hcl", "models", "-o", "trace", "--no-color"}

// BTC/USD
func ExampleNewModelsCmd_BTC_USD() {
	os.Args = append(args, "BTC/USD")
	main()
	// Output:
	// Model for BTC/USD:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
}

// ETH/BTC
func ExampleNewModelsCmd_ETH_BTC() {
	os.Args = append(args, "ETH/BTC")
	main()
	// Output:
	// Model for ETH/BTC:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/BTC)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/BTC)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/BTC)
	//       └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/BTC)
}

// ETH/USD
func ExampleNewModelsCmd_ETH_USD() {
	os.Args = append(args, "ETH/USD")
	main()
	// Output:
	// Model for ETH/USD:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       └──indirect()
	//          ├──alias(alias:ETH/USDC)
	//          │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//          └──reference()
	//             └──median(min_values:2)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//                └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}

// GNO/USD
func ExampleNewModelsCmd_GNO_USD() {
	os.Args = append(args, "GNO/USD")
	main()
	// Output:
	// Model for GNO/USD:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──indirect()
	//       │  ├──alias(alias:ETH/GNO)
	//       │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:WETH/GNO)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       │        └──indirect()
	//       │           ├──alias(alias:ETH/USDC)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//       │           └──reference()
	//       │              └──median(min_values:2)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
	//       ├──indirect()
	//       │  ├──alias(alias:GNO/ETH)
	//       │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:GNO/WETH)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       │        └──indirect()
	//       │           ├──alias(alias:ETH/USDC)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//       │           └──reference()
	//       │              └──median(min_values:2)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:GNO/BTC)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       └──indirect()
	//          ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:GNO/USDT)
	//          └──reference()
	//             └──median(min_values:3)
	//                ├──indirect()
	//                │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
	//                │  └──reference()
	//                │     └──median(min_values:3)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//                │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//                ├──alias(alias:USDT/USD)
	//                │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
	//                └──indirect()
	//                   ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
	//                   └──reference()
	//                      └──median(min_values:3)
	//                         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//                         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//                         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//                         └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
}

// IBTA/USD
func ExampleNewModelsCmd_IBTA_USD() {
	os.Args = append(args, "IBTA/USD")
	main()
	// Output:
	// Model for IBTA/USD:
	// ───reference()
	//    └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:ishares, query:IBTA/USD)
}

// LINK/USD
func ExampleNewModelsCmd_LINK_USD() {
	os.Args = append(args, "LINK/USD")
	main()
	// Output:
	// Model for LINK/USD:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:LINK/BTC)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:LINK/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:LINK/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:LINK/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:LINK/USD)
	//       └──indirect()
	//          ├──alias(alias:LINK/ETH)
	//          │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:LINK/WETH)
	//          └──reference()
	//             └──median(min_values:3)
	//                ├──indirect()
	//                │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//                │  └──reference()
	//                │     └──median(min_values:3)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//                │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//                └──indirect()
	//                   ├──alias(alias:ETH/USDC)
	//                   │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//                   └──reference()
	//                      └──median(min_values:2)
	//                         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//                         └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}

// MATIC/USD
func ExampleNewModelsCmd_MATIC_USD() {
	os.Args = append(args, "MATIC/USD")
	main()
	// Output:
	// Model for MATIC/USD:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:MATIC/USDT)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──alias(alias:USDT/USD)
	//       │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
	//       │        └──indirect()
	//       │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
	//       │           └──reference()
	//       │              └──median(min_values:3)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:MATIC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:MATIC/USD)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:huobi, query:MATIC/USDT)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──alias(alias:USDT/USD)
	//       │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
	//       │        └──indirect()
	//       │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
	//       │           └──reference()
	//       │              └──median(min_values:3)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:MATIC/USD)
}

// MKR/ETH
func ExampleNewModelsCmd_MKR_ETH() {
	os.Args = append(args, "MKR/ETH")
	main()
	// Output:
	// Model for MKR/ETH:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:MKR/BTC)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/BTC)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/BTC)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/BTC)
	//       │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/BTC)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:MKR/USD)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       │        └──indirect()
	//       │           ├──alias(alias:ETH/USDC)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//       │           └──reference()
	//       │              └──median(min_values:2)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:MKR/USD)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       │        └──indirect()
	//       │           ├──alias(alias:ETH/USDC)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//       │           └──reference()
	//       │              └──median(min_values:2)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:MKR/USD)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       │        └──indirect()
	//       │           ├──alias(alias:ETH/USDC)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//       │           └──reference()
	//       │              └──median(min_values:2)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
	//       └──indirect()
	//          ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:MKR/USD)
	//          └──reference()
	//             └──median(min_values:3)
	//                ├──indirect()
	//                │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//                │  └──reference()
	//                │     └──median(min_values:3)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//                │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//                └──indirect()
	//                   ├──alias(alias:ETH/USDC)
	//                   │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//                   └──reference()
	//                      └──median(min_values:2)
	//                         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//                         └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}

// MKR/USD
func ExampleNewModelsCmd_MKR_USD() {
	os.Args = append(args, "MKR/USD")
	main()
	// Output:
	// Model for MKR/USD:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:MKR/BTC)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:MKR/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:MKR/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:MKR/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:MKR/USD)
	//       ├──indirect()
	//       │  ├──alias(alias:MKR/ETH)
	//       │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:MKR/WETH)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       │        └──indirect()
	//       │           ├──alias(alias:ETH/USDC)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//       │           └──reference()
	//       │              └──median(min_values:2)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
	//       └──indirect()
	//          ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:MKR/USDC)
	//          └──reference()
	//             └──median(min_values:2)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//                └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}

// RETH/ETH
func ExampleNewModelsCmd_RETH_ETH() {
	os.Args = append(args, "RETH/ETH")
	main()
	// Output:
	// Model for RETH/ETH:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──alias(alias:RETH/ETH)
	//       │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:RETH/WETH)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:RETH/WSTETH)
	//       │  └──reference()
	//       │     └──indirect()
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
	//       │        └──reference()
	//       │           └──median(min_values:2)
	//       │              ├──alias(alias:STETH/ETH)
	//       │              │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
	//       │              └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
	//       └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:rocketpool, query:RETH/ETH)
}

// RETH/USD
func ExampleNewModelsCmd_RETH_USD() {
	os.Args = append(args, "RETH/USD")
	main()
	// Output:
	// Model for RETH/USD:
	// ───reference()
	//    └──indirect()
	//       ├──reference()
	//       │  └──median(min_values:3)
	//       │     ├──alias(alias:RETH/ETH)
	//       │     │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:RETH/WETH)
	//       │     ├──indirect()
	//       │     │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:RETH/WSTETH)
	//       │     │  └──reference()
	//       │     │     └──indirect()
	//       │     │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
	//       │     │        └──reference()
	//       │     │           └──median(min_values:2)
	//       │     │              ├──alias(alias:STETH/ETH)
	//       │     │              │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
	//       │     │              └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
	//       │     └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:rocketpool, query:RETH/ETH)
	//       └──reference()
	//          └──median(min_values:3)
	//             ├──indirect()
	//             │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//             │  └──reference()
	//             │     └──median(min_values:3)
	//             │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//             │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//             │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//             │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//             └──indirect()
	//                ├──alias(alias:ETH/USDC)
	//                │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//                └──reference()
	//                   └──median(min_values:2)
	//                      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//                      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}

// STETH/ETH
func ExampleNewModelsCmd_STETH_ETH() {
	os.Args = append(args, "STETH/ETH")
	main()
	// Output:
	// Model for STETH/ETH:
	// ───reference()
	//    └──median(min_values:2)
	//       ├──alias(alias:STETH/ETH)
	//       │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
	//       └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
}

// USDC/USD
func ExampleNewModelsCmd_USDC_USD() {
	os.Args = append(args, "USDC/USD")
	main()
	// Output:
	// Model for USDC/USD:
	// ───reference()
	//    └──median(min_values:2)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}

// USDT/USD
func ExampleNewModelsCmd_USDT_USD() {
	os.Args = append(args, "USDT/USD")
	main()
	// Output:
	// Model for USDT/USD:
	// ───reference()
	//    └──median(min_values:3)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       ├──alias(alias:USDT/USD)
	//       │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
	//       └──indirect()
	//          ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
	//          └──reference()
	//             └──median(min_values:3)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//                └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
}

// WSTETH/ETH
func ExampleNewModelsCmd_WSTETH_ETH() {
	os.Args = append(args, "WSTETH/ETH")
	main()
	// Output:
	// Model for WSTETH/ETH:
	// ───reference()
	//    └──indirect()
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
	//       └──reference()
	//          └──median(min_values:2)
	//             ├──alias(alias:STETH/ETH)
	//             │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
	//             └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
}

// WSTETH/USD
func ExampleNewModelsCmd_WSTETH_USD() {
	os.Args = append(args, "WSTETH/USD")
	main()
	// Output:
	// Model for WSTETH/USD:
	// ───reference()
	//    └──indirect()
	//       ├──reference()
	//       │  └──indirect()
	//       │     ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
	//       │     └──reference()
	//       │        └──median(min_values:2)
	//       │           ├──alias(alias:STETH/ETH)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
	//       │           └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
	//       └──reference()
	//          └──median(min_values:3)
	//             ├──indirect()
	//             │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//             │  └──reference()
	//             │     └──median(min_values:3)
	//             │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//             │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//             │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//             │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//             ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//             └──indirect()
	//                ├──alias(alias:ETH/USDC)
	//                │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//                └──reference()
	//                   └──median(min_values:2)
	//                      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//                      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}

// YFI/USD
func ExampleNewModelsCmd_YFI_USD() {
	os.Args = append(args, "YFI/USD")
	main()
	// Output:
	// Model for YFI/USD:
	// ───reference()
	//    └──median(min_values:2)
	//       ├──indirect()
	//       │  ├──alias(alias:ETH/YFI)
	//       │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:WETH/YFI)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//       │        └──indirect()
	//       │           ├──alias(alias:ETH/USDC)
	//       │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//       │           └──reference()
	//       │              └──median(min_values:2)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:YFI/USDT)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──alias(alias:USDT/USD)
	//       │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
	//       │        └──indirect()
	//       │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
	//       │           └──reference()
	//       │              └──median(min_values:3)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:YFI/USD)
	//       ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:YFI/USD)
	//       ├──indirect()
	//       │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:YFI/USDT)
	//       │  └──reference()
	//       │     └──median(min_values:3)
	//       │        ├──indirect()
	//       │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
	//       │        │  └──reference()
	//       │        │     └──median(min_values:3)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       │        ├──alias(alias:USDT/USD)
	//       │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
	//       │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
	//       │        └──indirect()
	//       │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
	//       │           └──reference()
	//       │              └──median(min_values:3)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//       │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//       │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//       └──indirect()
	//          ├──alias(alias:YFI/ETH)
	//          │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:sushiswap, query:YFI/WETH)
	//          └──reference()
	//             └──median(min_values:3)
	//                ├──indirect()
	//                │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
	//                │  └──reference()
	//                │     └──median(min_values:3)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
	//                │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
	//                │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
	//                ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
	//                └──indirect()
	//                   ├──alias(alias:ETH/USDC)
	//                   │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
	//                   └──reference()
	//                      └──median(min_values:2)
	//                         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
	//                         └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
}
