version: '3'
services:
  spire:
    image: ghcr.io/chronicleprotocol/spire:0.0.0-dev.0
    build:
      context: "../.."
      dockerfile: "../../Dockerfile"
      args:
        APP_NAME: "spire"
        APP_VERSION: "0.0.0-dev.0"
