name: Publish Docker Images
# Build & Push rebuilds the tendermint docker image on every push to master and creation of tags
# and pushes the image to https://hub.docker.com/r/interchainio/simapp/tags
on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - dev-.+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Prepare
        id: prep
        run: |
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [[ "${{ github.event.repository.default_branch }}" == "$VERSION" ]]; then
              VERSION=dev
            fi
          fi
          echo ::set-output name=version::${VERSION}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image with all binaries
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chronicleprotocol/oracle-suite:${{ steps.prep.outputs.version }}

      - name: Build and Publish Spire Docker image to Github Packages
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile-spire
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chronicleprotocol/spire:${{ steps.prep.outputs.version }},ghcr.io/chronicleprotocol/spire:latest
      
      - name: Build and Publish Ghost Docker image to Github Packages
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile-ghost
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chronicleprotocol/ghost:${{ steps.prep.outputs.version }},ghcr.io/chronicleprotocol/ghost:latest

      - name: Build and Publish Leeloo Docker image to Github Packages
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile-leeloo
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chronicleprotocol/leeloo:${{ steps.prep.outputs.version }},ghcr.io/chronicleprotocol/leeloo:latest

      - name: Build and Publish Lair Docker image to Github Packages
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile-lair
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chronicleprotocol/lair:${{ steps.prep.outputs.version }},ghcr.io/chronicleprotocol/lair:latest

      - name: Build and Publish Spectre Docker image to Github Packages
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile-spectre
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chronicleprotocol/spectre:${{ steps.prep.outputs.version }},ghcr.io/chronicleprotocol/spectre:latest
