# TODO: Unify this workflow into a single one that is parameterized by the app name.
name: "Release Spire Docker Image"
on:
  workflow_dispatch: # Allow manual trigger
#  push:
#    tags:
#      - v[0-9]+.[0-9]+.[0-9]+
#      - v[0-9]+.[0-9]+.[0-9]+-[0-9]+
#      - v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/chronicleprotocol/spire
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./cmd/spire/Dockerfile
          build-args: |
            APP_VERSION=${{ steps.meta.outputs.version }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
