name: Publish Go Binaries
on:
  workflow_call:
    inputs:
      application:
        description: 'Application Name'
        type: string
        required: true

  workflow_dispatch:
    inputs:
      version:
        description: 'New Version (no `v` prefix)'
        type: string
        required: false
        default: ''
      application:
        description: 'Application Name (lowercase)'
        type: choice
        required: true
        options:
          - gofer
          - spire
          - ghost
          - spectre

jobs:
  go_releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -f .github/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
