name: Publish Go Binaries

on:
  workflow_call:
    inputs:
      snapshot:
        description: 'Application Snapshot'
        type: boolean
        default: false
        required: true
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Application Snapshot'
        type: boolean
        default: false
        required: true

jobs:
  go_releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -f .github/.goreleaser.yml ${{ inputs.snapshot && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
