name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Code linting & Unit tests
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Linting code
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.45
          args: --timeout=10m0s
      - name: Test
        run: make test
  test-e2e:
    name: E2E Tests
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start Smocker instance for testing
        run: docker run -d -p 8080:8080 -p 8081:8081 --name smocker thiht/smocker
      - name: Build E2E Tests in Docker
        run: docker build -t gofer_e2e -f e2e/gofer/Dockerfile .
      - name: Run E2E Test
        run: docker run -i --rm --link smocker gofer_e2e
  test-e2e-teleport:
    name: E2E Tests Teleport
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download vendors
        run: go mod vendor
      - name: Start Smocker instance for testing
        run: docker run -d -p 8080:8080 -p 8081:8081 --name smocker thiht/smocker
      - name: Run E2E Test (Ethereum)
        working-directory: ./e2e/teleport
        run: go test -run ^TestEthereum$
      - name: Run E2E Test (Starknet)
        working-directory: ./e2e/teleport
        run: go test -run ^TestStarknet$
  test-e2e-ghost:
    name: E2E Tests Ghost
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download vendors
        run: go mod vendor
      - name: Start Smocker instance for testing
        run: docker run -d -p 8080:8080 -p 8081:8081 --name smocker thiht/smocker
      - name: Run E2E Test (Ghost)
        working-directory: ./e2e/ghost
        run: go test -v -p 1 ./
